#!/usr/bin/env bash

set -e

EMPTY=$([ $(ls -A /var/www | egrep -v '._gems|bashrc' | wc -l) -eq 0 ] && echo 'true' || echo 'false')

if [ $EMPTY == 'true' ]; then
    echo "No files found in /var/www, attempting to get lock"
    (
        if flock -n 9; then
            mkdir public
            cp -r /usr/src/* /var/www
            
            #GEM_HOME=$SHARED_GEM_HOME
            #GEM_PATH=$SHARED_GEM_HOME
            #PATH=$GEM_PATH:$PATH
            
            #gem install -N bundler
            #bundle install
        else
            echo 'No lock, exiting'
            exit
        fi
    ) 9>/var/www/alockfile
    
    rm -f /var/www/alockfile
fi

/usr/bin/sync_gems.sh &
disown %1
echo "Giving bundler extra time to sync gems"
sleep 10


